### ISSUE TITLE
How did you calculate this value?

### ISSUE THREAD

**Issue by Edivad99** [darkarnium/plugin.video.nowtv#3]
How did you calculate this value?
https://github.com/darkarnium/plugin.video.nowtv/blob/1ade10b99928b20c72197350ee67fbe673104d46/scripts/patch_loader.py#L20

**Comment by darkarnium** [comment]
Hey there,

This was determined by reversing the `Now TV Player.exe` loader, to locate the code responsible for validating the signature of the ASAR. This block would then take one of two branches, one for if the signature matched the wanted value, and another if it did not.

https://github.com/darkarnium/plugin.video.nowtv/tree/master/scripts#patch-loader-patch_loaderpy

The block responsible for this operation was identified by debugging the process and waiting for events where the ASAR was read. The application was then single-stepped until this block responsible for validating the signature check was found. 

In later versions of the application, and rebranded versions for other providers, the location of the signature check may not have changed too much, so it may be possible to locate the new offsets using strings in and around the function - if any exist.

Unfortunately, I no longer use the service, so I do not have any more recent offsets.

Regards,
Peter
